# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

hidden_imports = [
    "ttkbootstrap",
    "ttkbootstrap.constants",
    "ttkbootstrap.style",
    "ttkbootstrap.themes",
    "ttkbootstrap.dialogs",
    "ttkbootstrap.scrolled",
    "ttkbootstrap.tooltip",
    "ttkbootstrap.tableview",
    "ttkbootstrap.validation",
    "tkinter",
    "tkinter.ttk",
    "tkinter.font",
    "tkinter.filedialog",
    "tkinter.messagebox",
    "tkinter.simpledialog",
    "tkinter.colorchooser",
    "PIL",
    "PIL.Image",
    "PIL.ImageDraw",
    "PIL.ImageFont",
    "PIL.ImageTk",
    "src",
    "src.app",
    "src.config",
    "src.core",
    "src.core.editor",
    "src.core.tab_manager",
    "src.core.syntax_highlighter",
    "src.core.file_manager",
    "src.core.terminal",
    "src.core.search",
    "src.core.git_manager",
    "src.ui",
    "src.ui.menubar",
    "src.ui.sidebar",
    "src.ui.statusbar",
    "src.ui.toolbar",
    "src.ui.file_tree",
    "src.ui.welcome",
    "src.ui.splash",
    "src.utils",
    "src.utils.theme_loader",
    "src.utils.recent_files",
    "src.utils.shortcuts",
    "src.utils.icon_manager",
    "assets.icons",
    "assets.icons.icons",
    "json",
    "os",
    "re",
    "subprocess",
    "threading",
    "sys",
    "io",
    "base64",
    "hashlib",
    "shutil",
    "signal",
    "math",
]

datas = [
    ("assets", "assets"),
    ("src", "src"),
]

a = Analysis(
    ["run.py"],
    pathex=["."],
    binaries=[],
    datas=datas,
    hiddenimports=hidden_imports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        "matplotlib", "numpy", "scipy",
        "pandas", "pytest", "setuptools", "distutils",
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name="OmniIDE",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)